config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :players, except: :show
  resources :battles, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
# frozen_string_literal: true

class Battle < ApplicationRecord
  belongs_to :player_1, class_name: 'Player'
  belongs_to :player_2, class_name: 'Player'
  belongs_to :winner, class_name: 'Player', optional: true
  belongs_to :loser, class_name: 'Player', optional: true

  validates :player_1_id, presence: true
  validates :player_2_id, presence: true
  validate :two_different_players

  def update_battle_scores
    self.score1 = player_1.score
    self.score2 = player_2.score
    save
  end

  def update_battle_winner_loser
    self.winner = winner_loser[:winner]
    self.loser = winner_loser[:loser]
    self.winner_score = winner_loser_score[:winner_score]
    self.loser_score = winner_loser_score[:loser_score]
    save
  end

  def adjust_life_attack
    winner.attack_points += 0.3
    loser.life_points -= 1
    winner.save
    loser.save
  end

  def two_different_players
    message = 'The two players must be different!'
    errors.add(:player_2_id, message) if player_2_id == player_1_id
  end

  private

  def winner_loser
    {
      winner: score1 > score2 ? player_1 : player_2,
      loser: score1 > score2 ? player_2 : player_1
    }
  end

  def winner_loser_score
    {
      winner_score: score1 > score2 ? score1 : score2,
      loser_score: score1 > score2 ? score2 : score1
    }
  end
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  has_many :primary_battles, class_name: 'Battle', foreign_key: 'player_1_id'
  has_many :secondary_battles, class_name: 'Battle', foreign_key: 'player_2_id'
  has_many :won_battles, class_name: 'Battle', foreign_key: 'winner_id'
  has_many :lost_battles, class_name: 'Battle', foreign_key: 'loser_id'

  mount_uploader :picture, PhotoUploader
  validates :name, uniqueness: true, presence: true
  validates :name, length: { minimum: 3, maximum: 13 }
  validates :strength_points, presence: true
  validates :intelligence_points, presence: true
  validates :magic_points, presence: true
  validates :strength_points, inclusion: 1..13
  validates :intelligence_points, inclusion: 1..13
  validates :magic_points, inclusion: 1..13
  validate :max_15_points
  validates :picture, allow_blank: true, format: {
    with: %r{\.gif|jpg|png}i, # rubocop:disable Style/RegexpLiteral
    message: 'must be a gif, jpg, or png image.'
  }

  def max_15_points
    total_skills = strength_points + intelligence_points + magic_points
    errors.add(:strength_points, 'Skill points > 15') if total_skills > 15
  end

  def score
    skills = [strength_points, intelligence_points, magic_points].shuffle!
    attack_points + skills[0] * 0.5 + skills[1] * 0.7 + skills[2] * 0.9
  end

  def victory_ratio
    won_battles.count.to_f / (primary_battles + secondary_battles).count.to_f
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base #:nodoc: all
end

app/controllers/battles_controller.rb
# frozen_string_literal: true

class BattlesController < ApplicationController #:nodoc:
  before_action :set_battle, only: :show
  before_action :set_players, only: %i[new create]

  def index
    @battles = Battle.all
  end

  def new
    @players_count = Player.count
    @battle = Battle.new
  end

  def create
    @battle = Battle.new(battle_params)
    if @battle.save
      AfterBattleService.new.update(@battle)
      redirect_to battle_path(@battle)
    else
      flash.now[:alert] = flash_alerts
      render :new
    end
  end

  def show
    @winner = @battle.winner unless @battle.draw
    @loser = @battle.loser unless @battle.draw
    @winner_score = @battle.winner_score unless @battle.draw
    @loser_score = @battle.loser_score unless @battle.draw
  end

  private

  def flash_alerts
    errors = @battle.errors.full_messages
    not_ok = "Player 2 can't be blank"
    ok = 'Please select two players'
    errors.map { |m| m.gsub(not_ok, ok) }.join(' - ')
  end

  def set_battle
    @battle = Battle.find(params[:id])
  end

  def set_players
    @players = Player.where('life_points > ?', 0.0).order(life_points: :desc)
  end

  def battle_params
    params.require(:battle).permit(:player_1_id, :player_2_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController #:nodoc:
  before_action :set_player, only: %i[edit update destroy]

  def index
    @players = Player.order(life_points: :desc)
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to new_battle_path
    else
      flash.now[:alert] = flash_alerts
      render :new
    end
  end

  def edit
    # edit method
  end

  def update
    if @player.update(player_params)
      redirect_to new_battle_path
    else
      render :edit
    end
  end

  def destroy
    @player.destroy
  end

  private

  def flash_alerts
    errors = @player.errors.full_messages
    not_ok = 'Strength points Skill points > 15'
    ok = 'The sum of magic, intelligence and strength points cannot exceed 15'
    errors.map { |m| m.gsub(not_ok, ok) }.join(' - ')
  end

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(
      :name,
      :picture,
      :strength_points,
      :intelligence_points,
      :magic_points
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/battles/index.html.erb
<div class="container">
  <div class="index-header">
    <h1>Battles</h1>
    <%= link_to "Launch a new battle", new_battle_path, class: 'btn-submit-small' %>
  </div>
  <% if @battles.empty? %>
    <div class="m-t-40">
      No battles were fought yet.
      <%= link_to "Launch your first battle!", new_battle_path, class: 'yellow-link' %>
    </div>
  <% else %>
    <table class="margin-dotted-table">
      <tr>
        <td><strong>Winner 👍</strong></td>
        <td></td>
        <td><strong>Loser 👎</strong></td>
        <td></td>
      </tr>
      <% @battles.each do |battle| %>
        <tr class="battle-item">
          <% if battle.score1 == battle.score2 %>
            <td></td>
            <td>Match nul!</td>
            <td></td>
          <% else %>
            <td>
              <%= battle.winner ? battle.winner.name : "Deleted player 😵" %><%=" - #{battle.winner_score}" if battle.winner %>
            </td>
            <td>VS</td>
            <td>
              <%= battle.loser ? battle.loser.name : "Deleted player 😵" %><%=" - #{battle.loser_score}" if battle.loser %>
            </td>
          <% end %>
          <td><p class="text-transparent m-b-0"><em><%= battle.created_at.strftime('%a, %B %e %Y - %l:%M %p') %></em></p></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/battles/new.html.erb
<div class="container">
  <% if @players.empty? %>
    <h1>Uh oh!</h1>
    <p class="text-transparent">You cannot launch a battle without any players!</p>
    <%= link_to "Create at least another player", new_player_path, class: 'btn-submit-small' %>
  <% elsif @players_count == 1 %>
    <h1>Uh oh!</h1>
    <p class="text-transparent">You cannot launch a battle with only one player!</p>
    <div class="player-item text-center width-100">
      <%= render 'shared/player_card', player: @players.first %>
    </div>
    <%= link_to "Create at least another player", new_player_path, class: 'btn-submit-small' %>
  <% else %>
    <h1>Choose two players 🤝</h1>
    <p class="text-transparent m-b-0">Click on the avatar of two players - you can also <%= link_to "create a new player", new_player_path, class: 'yellow-link' %>.</p>
    <p class="text-transparent m-b-0">- Be careful, if a player loses a battle, he loses a life <i class="fas fa-heart"></i>. If he wins, he gains attack points <i class="fas fa-fist-raised"></i>!</p>
    <p class="text-transparent">- When a player has lost all his lives, he cannot fight anymore! He's dead <i class="fas fa-dizzy"></i></p>
    <div class="player-list">
      <% @players.each do |player| %>
        <div class="player-item text-center <%= 'selected' if @battle.player_1_id == player.id %>" data-player-id=<%= "#{player.id}" %>>
          <%= render 'shared/player_card', player: player %>
        </div>
      <% end %>
    </div>
    <%= simple_form_for(@battle) do |f| %>
      <%= f.input :player_1_id, as: :hidden, error: false %>
      <%= f.input :player_2_id, as: :hidden, error: false %>
      <%= f.button :submit, 'Launch the battle!', class: "btn-submit" %>
    <% end %>
  <% end %>
</div>

app/views/battles/show.html.erb
<div class="container">
  <% if @battle.draw %>
    <h1 class="m-b-40">It's a tie!</h1>
    <p class="text-transparent">No one wins, the scores are equal.</p>
  <% else %>
    <h1 class="m-b-40"><%= @winner.name %> prevailed! 🏆</h1>
    <div class="result-content">
      <% if @winner.picture_url %>
        <%= cl_image_tag @winner.picture, height: 100, width: 100, crop: :thumb, gravity: :face %>
      <% else %>
        <%= image_tag 'avatar.png', class: 'avatar-large' %>
      <% end %>
      <p class="text-transparent fixed-width-p">After a long and grueling battle, <%= @winner.name %> won the fight.</p>
    </div>

    <h2 class="m-t-40">Battle recap:</h2>

    <p class="text-transparent m-b-0">
      <%= @winner.name %> gained 0.3 attack points!
    </p>
    <p class="text-transparent">
      <%= @loser.name %> lost a life :(
    </p>

    <table class="margin-dotted-table">
      <tr>
        <td></td>
        <td><%= @winner.name %> 👍</td>
        <td><%= @loser.name %> 👎</td>
      </tr>
      <tr>
        <td>Score</td>
        <td><%= @winner_score.round(1) %></td>
        <td><%= @loser_score.round(1) %></td>
      </tr>
      <tr>
        <td>Life points</td>
        <td><%= @winner.life_points %> <i class="fas fa-heart"></i></td>
        <td><%= @loser.life_points %> <i class="fas fa-heart"></i></td>
      </tr>
      <tr>
        <td>Attack points</td>
        <td><%= @winner.attack_points.round(1) %> <i class="fas fa-fist-raised"></i></td>
        <td><%= @loser.attack_points.round(1) %> <i class="fas fa-fist-raised"></i></td>
      </tr>
    </table>
  <% end %>

  <%= link_to "Launch new battle", new_battle_path, class: 'btn-submit-small' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Battle of Dagorlad</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' if !(params['controller'] == 'pages' && params['action'] == 'home') %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="welcome-banner">
  <div class="banner-content text-center">
    <h1>Welcome to the Plains of Dagorlad!</h1>
    <p>Replay the Battle of Dagorlad - for non-nerds, it's when Sauron loses his ring of power. 🤓</p>
    <p>⚡️ <strong>Create</strong> players 🤝 <strong>Pick</strong> two players 💥 <strong>Launch</strong> the battle 🥇 <strong>See</strong> who wins</p>
    <div class="home-cta">
      <%= link_to 'Enter the Battle Plains', new_battle_path, class: 'button-start' %>
    </div>
  </div>
</div>

app/views/players/_form.html.erb
<%= f.input :name, input_html: { class: 'form-input' }, error: false %>
<%= f.input :strength_points, label: 'Strength 💪', input_html: { class: 'form-input' }, error: false %>
<%= f.input :intelligence_points, label: 'Intelligence 💡', input_html: { class: 'form-input' }, error: false %>
<%= f.input :magic_points, label: 'Magic 💫', input_html: { class: 'form-input' }, error: false %>
<%= f.input :picture, error: false %>
<%= f.input :picture_cache, as: :hidden %>
<%= f.button :submit, class: 'btn-submit' %>

app/views/players/destroy.js.erb
document.querySelector("[data-player-id='<%= @player.id %>']").remove();

app/views/players/edit.html.erb
<div class="container">
  <h1>Modify your player:</h1>
  <div class="width-500">
    <%= simple_form_for @player, url: player_path(@player) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/players/index.html.erb
<div class="container">
  <div class="index-header">
    <h1>Players</h1>
    <%= link_to "Create a new player", new_player_path, class: 'btn-submit-small' %>
  </div>
  <% if @players.empty? %>
    <p class="m-b-0 m-t-40">Bummer! There are no players.</p>
    <p>Please create at least two players! ☝️</p>

  <% else %>
    <table class="margin-dotted-table text-center">
      <tr>
        <td></td>
        <td></td>
        <td><strong>Traits</strong></td>
        <td><strong>Lives</strong></td>
        <td><strong>Attack</strong></td>
        <td><strong>Victory %</strong></td>
        <td></td>
        <td></td>
      </tr>
      <% @players.each do |player| %>
        <tr data-player-id="<%= player.id %>">
          <td>
            <div class="player-picture">
              <div class="dead-player <%= 'display-none' if player.life_points >   0 %>">
                <i class="fas fa-dizzy"></i>
              </div>
              <% if player.picture_url %>
                <%= cl_image_tag player.picture, height: 100, width: 100, crop: :thumb, gravity: :face %>
              <% else %>
                <%= image_tag 'avatar.png', class: 'avatar-large' %>
              <% end %>
            </div>
          </td>
          <td><strong><%= player.name %></strong></td>
          <td>
            <div class="m-s-40">
              <span class="m-r-15">💡 <%= player.intelligence_points %></span>
              <span class="m-r-15">💫 <%= player.magic_points %></span>
              <span class="m-r-15">💪 <%= player.strength_points %></span>
            </div>
          </td>
          <td>
            <%= player.life_points %> <i class="fas fa-heart"></i>
          </td>
          <td>
            <%= player.attack_points %> <i class="fas fa-fist-raised"></i>
          </td>
          <td>
            <%= player.primary_battles.any? || player.secondary_battles.any? ? (player.victory_ratio * 100).round : "0"  %> %
          </td>
          <td>
            <%= link_to edit_player_path(player), class: 'yellow-link' do %>
              <i class="fas fa-edit"></i>
            <% end %>
          </td>
          <td>
            <%= link_to player_path(player), method: :delete, remote: true, class: 'yellow-link' do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/players/new.html.erb
<div class="container">
  <h1>Create your player</h1>

  <p class="text-transparent m-b-0">
    - You have only 15 points to distribute between Strength 💪, Magic 💫 and Intelligence 💡
  </p>
  <p class="text-transparent m-b-0">
    - Strength 💪, Magic 💫 and Intelligence 💡 must be between 0 and 13.
  </p>
  <p class="text-transparent">
    - Your player will have by default 3 life points <i class="fas fa-heart"></i> and 1 attack point <i class="fas fa-fist-raised"></i>.
  </p>

  <div class="width-500">
    <%= simple_form_for(@player) do |f| %>
      <%= render 'form', f:f %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="battle-navbar">
  <div class="navbar-left-content">
    <%= link_to root_path do %>
      <%= image_tag 'ring.png', class: 'logo' %>
    <% end %>
  </div>
  <div class="navbar-right-content">
    <p><%= link_to 'Players', players_path %></p>
    <p><%= link_to 'Battles', battles_path %></p>
    <%= link_to "Launch a new battle", new_battle_path, class: 'btn-submit-small-navbar cta-navbar' %>
  </div>
</div>

app/views/shared/_player_card.html.erb
<% if player.picture_url %>
  <%= cl_image_tag player.picture, height: 100, width: 100, crop: :thumb, gravity: :face %>
<% else %>
  <%= image_tag 'avatar.png', class: 'avatar-large' %>
<% end %>
<p><%= player.name %></p>
<p class="text-transparent"><%= player.life_points %> <i class="fas fa-heart"></i></p>